spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: manager
    url:  jdbc:oracle:thin:@localhost:1521/XE
    username: system
    jpa:
    hibernate:
    ddl-auto: update
    properties:
    hiberante:
    format_sql: true
    show_sql: true
