spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbms
    username: root
    password: sirivinni
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9090
